version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 15
  reviewers:
  - toshimaru
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  reviewers:
  - toshimaru
