name: 'Build'
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm install
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: npm run build
      - run: npm run lint
      - run: npm run test
