name: 'Check Diff'
on: [push, pull_request]
jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - name: Check Diff
        run: git diff --exit-code dist/index.js
