name: 'Link PR to Backlog'
on:
  pull_request:
    types: [opened, edited]
jobs:
  backlog-pr-link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - name: Test toshimaru/backlog-pr-link-action
        uses: ./ # Uses an action in the root directory
        with:
          backlog-api-key: "${{ secrets.BACKLOG_API_KEY }}"
          backlog-host: "${{ secrets.BACKLOG_HOST }}"
