name: 'Link Pull Request to Backlog issue'
on: [pull_request]
jobs:
  add-assignees:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test toshimaru/backlog-pr-action action
        uses: ./ # Uses an action in the root directory
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
